import type { RecordedStep } from './record.js';

export type ScriptOptions = {
  // Absolute path to `server/dist/src/client.js` and `scriptrun.js`, so the
  // generated script imports the tested runtime instead of duplicating it.
  clientModule: string;
  runtimeModule: string;
  out: string;
  format: 'tsv' | 'csv';
  delay: number;
  waitState: 'dom_stable' | 'network_idle' | 'none';
  capture?: string;
};

const NAV_OR_ACTION = new Set(['browser_open', 'browser_click', 'browser_press', 'browser_select', 'browser_type', 'browser_fill', 'browser_act', 'browser_scroll']);
const READ = new Set(['browser_evaluate', 'browser_snapshot', 'browser_inventory']);

// A page that just navigated or changed rarely exposes the next read's target
// yet, so the generator inserts a settle wait when the author did not.
export function withWaitHeuristics(steps: RecordedStep[], waitState: ScriptOptions['waitState']): RecordedStep[] {
  if (waitState === 'none') return steps;
  const out: RecordedStep[] = [];
  for (let index = 0; index < steps.length; index++) {
    const step = steps[index];
    out.push(step);
    const next = steps[index + 1];
    if (!next) continue;
    if (NAV_OR_ACTION.has(step.method) && READ.has(next.method)) {
      out.push({ method: 'browser_wait_for', params: { state: waitState }, replayable: true, label: 'auto-wait (generated)' });
    }
  }
  return out;
}

export function generateScript(file: string, steps: RecordedStep[], options: ScriptOptions): string {
  const nonReplayable = steps.filter(step => step.replayable === false);
  if (nonReplayable.length) {
    const first = nonReplayable[0];
    throw Object.assign(
      new Error(`Cannot generate a script: step "${first.method}" is not replayable (${first.reason ?? 'needs a selector'}). Fix the run file first.`),
      { code: 'NON_REPLAYABLE_STEP' }
    );
  }
  const prepared = withWaitHeuristics(steps, options.waitState);
  const name = file.split(/[\\/]/).pop()?.replace(/\.jsonl$/i, '') || 'workflow';
  const stepsJson = JSON.stringify(prepared, null, 2);
  return `// Auto-generated by fastmcp-browser — workflow "${name}".
// Deterministic runner: replays recorded steps, resolves {{placeholders}},
// expands repeat/forEach loops, and writes the captured dataset as ${options.format.toUpperCase()}.
// Regenerate with: node dist/src/cli.js export --script ${file} <out.mjs>
import { createRequire } from 'node:module';
import { callHost } from ${JSON.stringify(options.clientModule)};
import { runWorkflow } from ${JSON.stringify(options.runtimeModule)};

const require = createRequire(import.meta.url);

const STEPS = ${stepsJson};
const DEFAULTS = ${JSON.stringify({ out: options.out, format: options.format, delay: options.delay, capture: options.capture ?? null })};

function readFlag(name) {
  const index = process.argv.indexOf('--' + name);
  return index !== -1 ? process.argv[index + 1] : undefined;
}

async function hydrateUpload(params) {
  const { paths, ...rest } = params;
  if (!Array.isArray(paths)) throw new Error('browser_upload requires a paths array');
  const { readUploadFiles } = await import(${JSON.stringify(options.clientModule.replace(/client\.js$/, 'tools.js'))});
  return { ...rest, files: await readUploadFiles(paths) };
}

const port = Number(process.env.FASTMCP_PORT ?? 9229);
const token = process.env.FASTMCP_TOKEN ?? 'fastmcp-local-dev';
const browser = readFlag('browser');
const profile = readFlag('profile');
const delay = Number(readFlag('delay') ?? DEFAULTS.delay);
const format = (readFlag('format') ?? DEFAULTS.format) === 'csv' ? 'csv' : 'tsv';
const out = readFlag('out') ?? DEFAULTS.out;
const capture = readFlag('capture') ?? DEFAULTS.capture;

function timeoutFor(method, params) {
  if (method === 'browser_wait') return Math.min(180000, Number(params.milliseconds ?? 0) + 5000);
  if (method === 'browser_wait_for') return Math.min(180000, Number(params.timeoutMs ?? 30000) + 5000);
  return 60000;
}

async function call(method, params) {
  let payload = params;
  if (method === 'browser_upload') payload = await hydrateUpload(params);
  if (browser) payload = { ...payload, browser };
  if (profile) payload = { ...payload, profile };
  return callHost(port, token, method, payload, timeoutFor(method, payload));
}

const result = await runWorkflow({
  steps: STEPS,
  call,
  options: { out, format, delay, capture: capture ?? undefined }
});

process.stdout.write(JSON.stringify({ ok: true, file: ${JSON.stringify(file)}, steps: result.steps, rows: result.rows, output: result.output }) + "\\n");
`;
}
